name: Publish Core Package
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-core:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install all dependencies
        run: npm ci
        
      - name: Run tests in core package
        working-directory: ./packages/core
        run: npm test
        
      - name: Build core package
        working-directory: ./packages/core
        run: npm run build
        
      - name: Publish to npm from core directory
        working-directory: ./packages/core
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ZATCA SDK ${{ github.ref }}
          body: |
            ## What's Changed
            
            - Core package published to npm as @zatca-sdk/core
            - Sandbox ZATCA Phase-2 e-invoicing support
            - UBL XML generation and TLV QR code support
            - Cryptographic operations with secp256k1
            
            ## Installation
            
            ```bash
            npm install @zatca-sdk/core
            ```
            
            ## Quick Start
            
            ```bash
            npx zatca-sdk doctor
            npm run core-demo
            ```
            
            Full documentation: https://github.com/mouna-bassim/zatca-sdk
          draft: false
          prerelease: false
